### ISSUE TITLE
fails to build on linux swift 3.0 preview 4

### ISSUE THREAD

**Issue by chad3814** [hkellaway/Gloss#201]
I know it's probably not you favorite platform, but I'd love to use it in a server on linux. There are some errors building though:
```
~/Gloss$ swift build
Compile Swift Module 'Gloss' (6 sources)
/home/ubuntu/Gloss/Sources/Gloss.swift:78:35: error: argument labels '(identifier:)' do not match any available overloads
    dateFormatterISO8601.locale = Locale(identifier: "en_US_POSIX")
                                  ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/Gloss/Sources/Gloss.swift:78:35: note: overloads for 'Locale' exist with these partially matching parameter lists: (localeIdentifier: String), (coder: NSCoder)
    dateFormatterISO8601.locale = Locale(identifier: "en_US_POSIX")
                                  ^
/home/ubuntu/Gloss/Sources/Gloss.swift:82:43: error: type 'String' has no member 'gregorian'
    var gregorian = Calendar(identifier: .gregorian)
                                          ^~~~~~~~~
/home/ubuntu/Gloss/Sources/Decoder.swift:461:37: error: value of type 'String' has no member 'addingPercentEncoding'
                let encodedString = urlString.addingPercentEncoding(withAllowedCharacters: NSCharacterSet.urlQueryAllowed) {
                                    ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
Foundation.String:286:16: note: did you mean 'removingPercentEncoding'?
    public var removingPercentEncoding: String? { get }
               ^
/home/ubuntu/Gloss/Sources/Encoder.swift:84:45: error: value of type 'String' does not conform to expected dictionary value type 'AnyObject'
                return [key : dateFormatter.string(from: date)]
                              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:112:31: error: value of type '[String]' does not conform to expected dictionary value type 'AnyObject'
                return [key : dateStrings]
                              ^~~~~~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:153:31: error: value of type 'JSON' (aka 'Dictionary<String, AnyObject>') does not conform to expected dictionary value type 'AnyObject'
                return [key : json]
                              ^~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:180:31: error: value of type '[JSON]' does not conform to expected dictionary value type 'AnyObject'
                return [key : encodedArray]
                              ^~~~~~~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:210:27: error: value of type '[String : JSON]' does not conform to expected dictionary value type 'AnyObject'
            return [key : encoded]
                          ^~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:239:27: error: value of type '[String : [JSON]]' does not conform to expected dictionary value type 'AnyObject'
            return [key : encoded]
                          ^~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:320:31: error: value of type '[NSNumber]' does not conform to expected dictionary value type 'AnyObject'
                return [key : numbers]
                              ^~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:360:19: error: value of type '[NSNumber]' does not conform to expected dictionary value type 'AnyObject'
                                return [key : numbers]
                                              ^~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:400:31: error: value of type '[NSNumber]' does not conform to expected dictionary value type 'AnyObject'
                return [key : numbers]
                              ^~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:440:19: error: value of type '[NSNumber]' does not conform to expected dictionary value type 'AnyObject'
                                return [key : numbers]
                                              ^~~~~~~
/home/ubuntu/Gloss/Sources/Encoder.swift:459:31: error: value of type 'String' does not conform to expected dictionary value type 'AnyObject'
                return [key : absoluteURLString]
                              ^~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/ubuntu/swift-3.0-PREVIEW-4-ubuntu14.04/usr/bin/swift-build-tool -f /home/ubuntu/Gloss/.build/debug.yaml
```

(that was in the swift_3.0 branch, I'll see what I can fix and make a PR)

**Comment by hkellaway** [comment]
yeah, i don't use Linux and am not sure how to troubleshoot these issues really. :confused: would love to see that PR if you're able to

**Comment by tsheaff** [comment]
@hkellaway semi-unrelated question — when will `swift_3.0` branch be merged to master and pushed to pod trunk as a new version of the pod?

**Comment by hkellaway** [comment]
@tsheaff good q. i've yet to have time to download the latest and make sure things are in working order. once i do so, yes - you'll see a new major version

**Comment by illyaBakurov** [comment]
@hkellaway is it any timeline you could provide, just to schedule things properly?

**Comment by hkellaway** [comment]
@illyaBakurov i will work on it this coming weekend

**Comment by hkellaway** [comment]
will be giving it a once-over with fresh eyes tomorrow night then pushing to CocoaPods. branch `release/1.0.0` can be pointed to in the meanwhile, if desired.

**Comment by hkellaway** [comment]
tried to push to the master CocoaPods repo tonight - but encountered error (https://github.com/CocoaPods/CocoaPods/issues/5908). hope to resolve soon; apologies for delaying

**Comment by hkellaway** [comment]
version `1.0.0` has been released and is compatible with Swift 3.0! 🎉

**Comment by hkellaway** [comment]
i'm closing the original issue as preview 4 is no longer applicable
